controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: arm
    pose: home
