controller_list:
  - name: fake_cr12_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses per group
  - group: cr12_arm
    pose: cr12_arm