planner_configs:
  RRT:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  PRM:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstar:
    type: geometric::PRMstar
me6_arm:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRT
    - RRTstar
    - PRM
    - PRMstar
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.01
  # 禁用路径简化相关选项
  simplify: false
  max_corrections: 0
  use_approximate_ik: false
